### ISSUE TITLE
HTTP ERROR 401

### ISSUE THREAD

**Issue by JeffersonFarFan** [pierre-emmanuelJ/iptv-proxy#68]
Hi together, 

wanted to test this project with docker-compose because im no familiar with go. 
I have a valid and working .m3u file accessing with url. 

![image](https://user-images.githubusercontent.com/77587652/104853824-a6043680-5903-11eb-9c0a-f2dfd58fdedf.png)

Same color same value.

In this case i got an exception 401. (Unauthorized).

Tested the same with same .m3u as local file. 

![image](https://user-images.githubusercontent.com/77587652/104853884-0e531800-5904-11eb-9d28-c7dd5308b06a.png)
got this error. yellow = username; red =  password

**Comment by pierre-emmanuelJ** [comment]
It seems you have a duplicated entry in your m3u file. since your playlist url is from an xtream provider 
you can leave blank this ones:
![image](https://user-images.githubusercontent.com/15922119/105179811-0e346180-5b2a-11eb-9c1f-fdcffa5ce199.png)
the proxy will auto detect the xtream credentials. and it should solve your problem

**Comment by pierre-emmanuelJ** [comment]
Closing due to an inactivity
